export const FormElements = {
  details: [
    {
      id: 1,
      name: "firstName",
      type: "text",
      placeholder: "Enter Your First Name",
      label: "First Name",
      required: true,
      disabled: false,
    },
    {
      id: 2,
      name: "lastName",
      type: "text",
      placeholder: "Enter Your Last Name",
      label: "Last Name",
      required: false,
      disabled: false,
    },
    {
      id: 3,
      name: "mobile",
      type: "number",
      placeholder: "Enter Your Mobile No.",
      label: "Mobile",
      required: true,
      disabled: false,
    },
    {
      id: 4,
      name: "email",
      type: "text",
      placeholder: "Enter Your Email address",
      label: "Email",
      required: true,
      disabled: false,
    },
    {
      id: 5,
      name: "qualification",
      type: "text",
      placeholder: "Enter Your Qualification",
      label: "Qualification",
      required: true,
      disabled: false,
    },
    {
      id: 6,
      name: "specialization",
      type: "text",
      placeholder: "Enter Your specialization",
      label: "Specialization",
      required: true,
      disabled: false,
    },
    {
      id: 7,
      name: "company",
      type: "text",
      placeholder: "Enter Your Company Name",
      label: "Company",
      required: true,
      disabled: false,
    },
    {
      id: 8,
      name: "position",
      type: "text",
      placeholder: "Enter Your Role",
      label: "Position",
      required: true,
      disabled: false,
    },
    {
      id: 9,
      name: "skillSet",
      type: "text",
      placeholder: "Enter Your Primary Skill",
      label: "Skills",
      required: true,
      disabled: false,
    },
  ],
};
export const HEADER_IMAGE =
  "https://pbs.twimg.com/profile_images/1612754698641248256/i97BA_zj_400x400.png";

export const SIDEBAR_ITEMS = [
  {
    id: 1,
    label: "Add User",
    path: "create",
    className: "active",
  },
  {
    id: 2,
    label: "Listed Users",
    path: "edit",
  },
];

export const TABLE_HEADERS = [
  "firstName",
  "lastName",
  "mobile",
  "email",
  "qualification",
  "specialization",
  "company",
  "position",
  "country",
  "state",
  "districts",
  "city",
];
